########################
## Basic parameters


## Sample information file with five columns: id / name / group / fq1 / fq2
src_sampleInfo	= "sample.tsv"
cluster_yml		= os.environ["CUTLERY"] + "/Snakemake.bySample/cluster.yml"

## Essential reference data
## Other user-defined files can be used.
## Mouse
genomeFa	= "/data/limlab/Resource/GenomeData/mm/mm10/Genome/genome.fa"
chrom_size	= "/data/limlab/Resource/GenomeData/mm/mm10/Genome/chrom.size"
peak_mask	= "/data/limlab/Resource/GenomeData/mm/mm10/ENCODE-blacklist.bed"
genome		= "mm10"
## Human
#genomeFa	= "/data/limlab/Resource/GenomeData/hg/hg38/Genome/genome.fa"
#chrom_size	= "/data/limlab/Resource/GenomeData/hg/hg38/Genome/chrom.size"
#peak_mask	= "/data/limlab/Resource/GenomeData/hg/hg38/ENCODE-blacklist.bed"
#genome		= "hg38"


## Other essential pameters
adapter     = "AGATCGGAAGAGC"	# illumina universal adapter in default
#adapter     = "CTGTCTCTTATA"	# Nextera adapter for ATAC-seq or Cut&Tag
#trim_maxLen=100	## Maximum read length after trimming. ** NOT YET IMPLEMENTED **
trim_minLen		= 20	# minimum fragment length. shorter fragments after trimming will be discarded
trim_minQual	= 20	# minimum quality for quality trimming

## Regular expressions for chromosome names
## Target chromosomes + spikein chromosome (if needed)
## This is also useful in excluding all the scaffold and random chromosomes
chrRegexAll		= "^chr[0-9XY]+$"
## Target chromosomes
chrRegexTarget	= "^chr[0-9XY]+$"
## Spike-in chromosomes, i.e. ec-chr for E coli chromosme (defined by Lim), NULL if not needed
spikePrefix		= "NULL"

########################
## STAR index & options
## Other STAR index also available under /data/limlab/Resource/STAR_Index/2.7.4
## If not, send a request to Lim Lab
star_index	= "/data/limlab/Resource/STAR_Index/2.7.4/mm10_allChr_vM20"
star_module	= "STAR/2.7.4"

## STAR alignment options
star_option	= "--alignSJDBoverhangMin 999 --alignIntronMax 1 --alignMatesGapMax 1000 --outFilterMultimapNmax 1 --outFilterMismatchNoverLmax 0.05 --outReadsUnmapped None --alignEndsProtrude 2 ConcordantPair"
## Note:
## Additoinal star_option to prevent soft-clipping: "--alignEndsType EndToEnd"
## BAM sort by "--outSAMtype" is handled by the star.align.sh by -s option.
## To keep unmapped reads in the output bam file, add "--outSAMunmapped Within"

#########################
## Job flags
doTrim		= True		## Perform adapter trimming, recommended
doDedup		= False		## Perform deduplication, not recommended

#########################
## Directories
fastqDir	= "0.Fastq"			# Directory containing fastq files
trimDir		= "0.Fastq.Trim"	# Directory for trimmed fastq files
alignDir	= "1.1.Align"		# Directory for alignment results
filteredDir	= "1.2.Align.filtered"	# Directory for filtered alignment results, i.e. chromosome, 
dedupDir	= "1.3.Align.dedup"	# ignored if doDeup==False
qcDir		= "2.1.QualityControl"

sampleDir	= "3.Sample"

#########################################
## Parameters for k-mer bias correction
kmer_genome	= "%s/limlab/Resource/Jellyfish.Kmer/%s.6mer.txt" % ( baseDir, genome )
kmer_pseudo	= 1




################################################
## Loading sample Information & cluster config
import pandas as pd
import sys
samples = pd.read_csv(src_sampleInfo, sep="\t", comment="#", na_filter=False)

import yaml
with open(os.path.expanduser(cluster_yml), 'r') as fh:
	cluster = yaml.load(fh)


#################################################
## Configuration & sample sheet validation
include: os.environ["CUTLERY"] + "/Snakemake.bySample/validate.smk"


#########################
## Rules start
# All sample names (Name field in sample.tsv file)
sampleList = samples.Name.tolist()
# Samples for TF (or narrow peaks)
sampleListFactor = samples.Name[samples.PeakMode=="factor"].tolist()
# Samples for histone modification (or broad peaks)
sampleListHistone = samples.Name[samples.PeakMode=="histone"].tolist()

rule all:
	input:
		## QC output
		expand(sampleDir + "/{sampleName}/QC/fragLen.dist.{ext}", sampleName=sampleList, ext=["txt","png"]),
#		expand(sampleDir + "/{sampleName}/QC/enrich.acor.{ext}", sampleName=sampleList, ext=["txt","png"]),
		expand(sampleDir + "/{sampleName}/QC/base_freq.{ext}",  sampleName=sampleList, ext=["png","html"]),
		qcDir + "/alignStat.txt",
		#spikeinCntDir + "/spikein.txt"
		## bigWig files	
		expand(sampleDir + "/{sampleName}/igv.{fragment}.ctr.bw", sampleName=sampleList, fragment=["all","nfr","nuc"]),
		expand(sampleDir + "/{sampleName}/igv.1bp.{strand}.bw", sampleName=sampleListFactor, strand=["plus","minus"]),
		expand(sampleDir + "/{sampleName}/igv.1bp.corrected{kmer_pseudo}.{strand}.bw", sampleName=sampleListFactor, kmer_pseudo=kmer_pseudo, strand=["plus","minus"]),
		expand(sampleDir + "/{sampleName}/igv.all.con.bw", sampleName=sampleList),
		## peak files
		expand(sampleDir + "/{sampleName}/HomerPeak.factor/peak.exBL.1rpm.bed", sampleName=sampleListFactor),
		expand(sampleDir + "/{sampleName}/HomerPeak.histone/peak.exBL.bed", sampleName=sampleListHistone),
		expand(sampleDir + "/{sampleName}/HomerPeak.factor/heatmap.exBL.1rpm.png", sampleName=sampleListFactor),
		expand(sampleDir + "/{sampleName}/Motif/Homer.all/homerResults.html", sampleName=sampleListFactor),
		expand(sampleDir + "/{sampleName}/Motif/MEME.random5k/meme-chip.html", sampleName=sampleListFactor),
		#expand(sampleDir + "/{sampleName}/Motif/Homer.all.allFrag/homerResults.html", sampleName=sampleListFactor),
		#expand(sampleDir + "/{sampleName}/Motif/MEME.random5k.allFrag/meme-chip.html", sampleName=sampleListFactor)
		## Footprint
		expand(sampleDir + "/{sampleName}/Footprint.Homer.default/cnr.4.complete", sampleName=sampleListFactor),
		expand(sampleDir + "/{sampleName}/Footprint.Homer.corrected{kmer_pseudo}/cnr.4.complete", sampleName=sampleListFactor, kmer_pseudo=kmer_pseudo)


include: os.environ["CUTLERY"] + "/Snakemake.bySample/rules.pre.smk"
include: os.environ["CUTLERY"] + "/Snakemake.bySample/rules.post.smk"

